export const PHONEBOOK_FIRST_LOAD = 'PHONEBOOK_FIRST_LOAD'
export const PHONEBOOK_LIST_UPDATE = 'PHONEBOOK_LIST_UPDATE'
export const PHONEBOOK_SEARCH_CHANGE = 'PHONEBOOK_SEARCH_CHANGE'
export const PHONEBOOK_LOADING = 'PHONEBOOK_LOADING'
